export const customersJSON = [
  {
    checked: true,
    name: "DemoName8",
    email: "abc@gmail.com2",
    createdAt: new Date("2022-03-6"),
    dueDate: new Date("2022-03-23"),
    amount: 10,
    status: "Completed",
  },
  {
    checked: true,
    name: "DemoName2",
    email: "abc@gmail.com8",
    createdAt: new Date("2022-03-23"),
    dueDate: new Date("2022-03-24"),
    amount: 20,
    status: "Draft",
  },
  {
    checked: true,
    name: "DemoName3",
    email: "abc@gmail.com7",
    createdAt: new Date("2022-03-26"),
    dueDate: new Date("2022-03-27"),
    amount: 50,
    status: "Draft",
  },
  {
    checked: true,
    name: "DemoName4",
    email: "abc@gmail.com6",
    createdAt: new Date("2022-03-28"),
    dueDate: new Date("2022-03-29"),
    amount: 60,
    status: "Draft",
  },
  {
    checked: true,
    name: "DemoName5",
    email: "abc@gmail.com5",
    createdAt: new Date("2022-03-30"),
    dueDate: new Date("2022-03-1"),
    amount: 70,
    status: "Draft",
  },
  {
    checked: true,
    name: "DemoName6",
    email: "abc@gmail.com4",
    createdAt: new Date("2022-03-2"),
    dueDate: new Date("2022-03-3"),
    amount: 80,
    status: "Draft",
  },
  {
    checked: true,
    name: "DemoName7",
    email: "abc@gmail.com3",
    createdAt: new Date("2022-03-4"),
    dueDate: new Date("2022-03-5"),
    amount: 100,
    status: "Draft",
  },
];
